#yaml file for creating the rett_recall scripting environ.
name: rett_memory
dependencies:
    - numpy
    - scipy
    - matplotlib
    - pandas
    - ipython
    - tifffile
    - pillow
    - scikit-image
    - pytest
    - notebook
    - graphviz
    - pydot
    - xlrd
