name: 🔴 BUG
description: File a bug/issue
labels: [Bug]
body:

# validate if this issue already exist
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please search to see if this issue already exists for this bug.
    options:
    - label: I have searched the existing issues
  validations:
      required: true

# input for a title for this bug
- type: input
  attributes:
    label: Title
    placeholder: "A short title for the bug"
  validations:
    required: true

# What user is experiencing box
- type: textarea
  attributes:
    label: Current Behavior
    description: A concise description of what you're experiencing.
  validations:
    required: false

# What user was expecting box
- type: textarea
  attributes:
    label: Expected Behavior
    description: A concise description of what you expected to happen.
  validations:
    required: false

# Steps to reproduce box
- type: textarea
  attributes:
    label: Steps To Reproduce
    description: Steps to reproduce the behavior.
    placeholder: |
      1. In this environment...
      2. With this config...
      3. Run '...'
      4. See error...
  validations:
    required: false

# input for users OS
- type: input
  attributes:
    label: Environment
    placeholder: "Ubuntu 20.04"
    validations:
      required: true

# Anything else
- type: textarea
  attributes:
    label: Anything else?
    description: |
      Links, references, images that will give us more context about the issue?

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
